id: P626AF4A6
initial_creation_type: input
source_metadata:
  Title: ''
  Editor: Dwivedi, Vajravallabha & Thinlay Ram Shashni
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1990'
  बौद्ध तन्त्र कोश (1):
    Text Version: Devanagari
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:59:56.226354'
last_modified_at: '2022-03-08T16:59:56.226365'
